-- MySQL Script generated by MySQL Workbench
-- Tue 29 Apr 2014 07:18:46 PM MST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema art_journey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `art_journey` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `art_journey` ;

-- -----------------------------------------------------
-- Table `art_journey`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `art_journey`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `last_login` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `art_journey`.`image_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `art_journey`.`image_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `submitter_user_id` INT NOT NULL,
  `content_uri` VARCHAR(100) NULL,
  `thumbnail_uri` VARCHAR(100) NULL,
  `author` VARCHAR(100) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `submitter_user_id_idx` (`submitter_user_id` ASC),
  CONSTRAINT `fk_submitter_user_id`
    FOREIGN KEY (`submitter_user_id`)
    REFERENCES `art_journey`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `art_journey`.`image_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `art_journey`.`image_attribute` (
  `attribute` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `image_data_id` INT NOT NULL,
  PRIMARY KEY (`id`, `image_data_id`),
  INDEX `fk_image_attributes_image_data1_idx` (`image_data_id` ASC),
  CONSTRAINT `fk_image_attributes_image_data1`
    FOREIGN KEY (`image_data_id`)
    REFERENCES `art_journey`.`image_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `art_journey`.`journey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `art_journey`.`journey` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `comments` TEXT NOT NULL,
  `creation_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `art_journey`.`journey_image_data_assoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `art_journey`.`journey_image_data_assoc` (
  `journey_id` INT NOT NULL,
  `image_data_id` INT NOT NULL,
  PRIMARY KEY (`journey_id`, `image_data_id`),
  INDEX `fk_journey_has_image_data_image_data2_idx` (`image_data_id` ASC),
  INDEX `fk_journey_has_image_data_journey2_idx` (`journey_id` ASC),
  CONSTRAINT `fk_journey_has_image_data_journey2`
    FOREIGN KEY (`journey_id`)
    REFERENCES `art_journey`.`journey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journey_has_image_data_image_data2`
    FOREIGN KEY (`image_data_id`)
    REFERENCES `art_journey`.`image_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
